In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print("1D array")
a

1D array


array([1, 2, 3])

In [5]:
a.dtype

dtype('int32')

In [8]:
type(a)  # kiểu dữ liệu của biến
print("Type: ", type(a))

Type:  <class 'numpy.ndarray'>


In [9]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ], 
    [
        [7,8,9],
        [10,11,12]
    ]
])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
d = np.array(
    [
        [1, 2, 3]
    ]
)
d

array([[1, 2, 3]])

In [13]:
arrays = [a, b, c, d]
for i in arrays:
    print("Kích thước các mảng:\n", np.shape(i))

Kích thước các mảng:
 (3,)
Kích thước các mảng:
 (2, 3)
Kích thước các mảng:
 (2, 2, 3)
Kích thước các mảng:
 (1, 3)


In [14]:
print('\nkích thước mảng a ',a.shape)
print('kích thước mảng b',b.shape)
print('kích thước mảng c',c.shape)
print('kích thước mảng d',d.shape, '\n')


kích thước mảng a  (3,)
kích thước mảng b (2, 3)
kích thước mảng c (2, 2, 3)
kích thước mảng d (1, 3) 



In [15]:
print("Matrix of ones", np.ones((2,2)))  # yêu cầu: tạo ma trận các phần tử đều là 1 kích thước (2, 2)
print("Matrix of zeros", np.zeros((2,2)))  # yêu cầu: tạo ma trận các phần tử đều là 0 kích thước (2, 2)  # np.zeros()
print("Identity matrix", np.eye(3))  # yêu cầu: tạo ma trận đơn vị 3 chiều  # np.eye()
print("Random matrix", np.random.randint(0,2,(3,3)))  # yêu cầu: tạo ma trận ngẫu nhiên các phần tử nằm trong khoảng (0, 1) kích thước (3, 3)  # np.random.rand()

Matrix of ones [[1. 1.]
 [1. 1.]]
Matrix of zeros [[0. 0.]
 [0. 0.]]
Identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random matrix [[0 0 1]
 [0 1 0]
 [1 1 0]]


In [16]:
print("Matrix of ones")  # yêu cầu: tạo ma trận các phần tử đều là 1 kích thước (2, 2)  # np.ones()
print(np.ones((2,2)))
print("Matrix of zeros")  # yêu cầu: tạo ma trận các phần tử đều là 0 kích thước (2, 2)  # np.zeros()
print(np.zeros((2,2)))
print("Identity matrix")  # yêu cầu: tạo ma trận đơn vị 3 chiều  # np.eye()
print(np.eye(3, dtype = float))
print("Random matrix")  # yêu cầu: tạo ma trận ngẫu nhiên các phần tử nằm trong khoảng (0, 1) kích thước (3, 3)  # np.random.rand()
print(np.random.rand(3,3))

Matrix of ones
[[1. 1.]
 [1. 1.]]
Matrix of zeros
[[0. 0.]
 [0. 0.]]
Identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random matrix
[[0.41315799 0.86480651 0.97058063]
 [0.07964497 0.99312623 0.9149731 ]
 [0.98340564 0.35234936 0.7648113 ]]


In [18]:
dfshbsad = np.ones((2,2))
dfshbsad

array([[1., 1.],
       [1., 1.]])

In [19]:
a = np.array([[1,0,2],
              [2,3,0]])
b = np.array([[2,1,-1],
              [2,1,2]])
c = np.array([[2,1],
              [0,2],
              [1,2]])

In [20]:
print('Tổng hai ma trận: \n{}'.format(a + b))
# yêu cầu: in ra màn hình a - b
print('Hiệu hai ma trận: \n{}'.format(a - b))
# yêu cầu: in ra màn hình a * b
print('Tích hai ma trận: \n{}'.format(a * b))
print('Nhân hai ma trận: \n{}'.format(np.dot(a, c)))

Tổng hai ma trận: 
[[3 1 1]
 [4 4 2]]
Hiệu hai ma trận: 
[[-1 -1  3]
 [ 0  2 -2]]
Tích hai ma trận: 
[[ 2  0 -2]
 [ 4  3  0]]
Nhân hai ma trận: 
[[4 5]
 [4 8]]


In [25]:
# # # yêu cầu: in ra màn hình a - 1
# # print ('\n a - 1: ', a-1)
# # # yêu cầu: in ra màn hình a - b
# # print ('\n a - b: ', a-b)
# # # yêu cầu: in ra màn hình a - c
# # print ('\n a -c: ', a-c)
# # yêu cầu: in ra màn hình a - 1
# print("In ra màn hình a - 1: \n{}".format(a-1))
# # yêu cầu: in ra màn hình a - b
# print("\nIn ra màn hình a - b: \n{}".format(a - b))
# # yêu cầu: in ra màn hình a - c
# print("In ra màn hình a - c: \n{}".format(a - c))
# yêu cầu: in ra màn hình a - 1
print(a-1)
# yêu cầu: in ra màn hình a - b
print(a-b)
# yêu cầu: in ra màn hình a - c
print(a-c)

[[ 0 -1  1]
 [ 1  2 -1]]
[[-1 -1  3]
 [ 0  2 -2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [26]:
b = np.array([[2,1,-1],
              [2,1,2]])
b.T

array([[ 2,  2],
       [ 1,  1],
       [-1,  2]])

In [27]:
print("Chuyển vị ma trận b: \n{}".format(np.transpose(b)))

Chuyển vị ma trận b: 
[[ 2  2]
 [ 1  1]
 [-1  2]]


In [29]:
print('\nnhân ma trận ', np.matmul(a,b.T))
print("Nhân ma trận np.matmul: \n{}".format(np.matmul(a, np.transpose(b))))


nhân ma trận  [[0 6]
 [7 7]]
Nhân ma trận np.matmul: 
[[0 6]
 [7 7]]


In [30]:
import numpy as np

# Sử dụng numpy.dot
a_ = np.array([[1, 0], [0, 1]])
b_ = np.array([[4, 1], [2, 2]])
print(np.dot(a_, b_))  # Output: [[4, 1], [2, 2]]
print(np.dot(a_, 5))  # Output: [[4, 1], [2, 2]]

# Sử dụng numpy.matmul
print(np.matmul(a_, b_))  # Output: [[4, 1], [2, 2]]
print(np.matmul(a_, 5))  # Output: [[4, 1], [2, 2]]

[[4 1]
 [2 2]]
[[5 0]
 [0 5]]
[[4 1]
 [2 2]]


ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [32]:
a = np.array([
    [1,0,2],
    [2,3,0]
])
a[1,0]

2

In [33]:
a[1, :]

array([2, 3, 0])

In [34]:
a[:,1]

array([0, 3])

In [35]:
a[:2, :2]

array([[1, 0],
       [2, 3]])

In [36]:
mask = a>=2
mask

array([[False, False,  True],
       [ True,  True, False]])

In [37]:
a >= 2

array([[False, False,  True],
       [ True,  True, False]])

In [38]:
a[mask]

array([2, 2, 3])

In [39]:
a[0,1] = 5
a

array([[1, 5, 2],
       [2, 3, 0]])

In [40]:
a.reshape((3,2))

array([[1, 5],
       [2, 2],
       [3, 0]])

In [47]:
a.reshape((1,-1000))

array([[1, 5, 2, 2, 3, 0]])

In [48]:
a[:,0] = np.zeros((,))
a

array([[0, 5, 2],
       [0, 3, 0]])

In [59]:
dhd = np.zeros((0,))
dhd

array([], dtype=float64)

In [51]:
a[:,0]

array([1, 2])

In [58]:
a[:,0] = np.zeros((1,))
a

array([[0, 0, 2],
       [0, 3, 0]])

In [50]:
a = np.array([
    [1,0,2],
    [2,3,0]
])
a

array([[1, 0, 2],
       [2, 3, 0]])